### ISSUE TITLE
Wine not downloading .Net Framework

### ISSUE THREAD

**Issue by kiyokodyele** [mmtrt/cncra2yr#9]
after installation, a prompt is telling me that .net framework is needed to install from wine. After clicking install, it  tries to download but the progress is not moving even for a long time. How can i resolve this? I am using debian/deepin-15.10.2 distro.

**Comment by mmtrt** [comment]
I've just reinstalled snap and tested to ingame it is working fine for me. Can you provide screenshot of this issue where this happens.

Maybe try to reinstall snap after removing.

**Comment by kiyokodyele** [comment]
![DeepinScreenshot_select-area_20190718005606](https://user-images.githubusercontent.com/45057955/61395004-feb1d800-a8f6-11e9-8f2a-e0eae5e4b273.png)
after clicking "Install" button, it says "Downloading..." but progress bar doesn't seems to move.

**Comment by kiyokodyele** [comment]
running the game using `$ sudo snap run cncra2yr`
```
mkdir: cannot create directory ‘/run/user/0’: Permission denied
------------------------------------------------------
Running Wine/winetricks as root is highly discouraged. See https://wiki.winehq.org/FAQ#Should_I_run_Wine_as_root.3F
------------------------------------------------------
------------------------------------------------------
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
------------------------------------------------------
Your version of wine 3.0.4 is no longer supported upstream. You should upgrade to 4.x
------------------------------------------------------
Using winetricks 20190615-next - sha256sum: 5bcdadda63aa02330e33861197bfbcb3d72711ca6ca1f5d87e03f6953ca764d8 with wine-3.0.4 and WINEARCH=win64
Failed to Fopen file /etc/wgetrc
Failed to Fopen file /etc/wgetrc
wget: Cannot read /etc/wgetrc (Permission denied).
------------------------------------------------------
Github down? version '' doesn't appear to be a valid version
------------------------------------------------------
Executing w_do_call xna40
Executing load_xna40 
------------------------------------------------------
Working around wine bug 30718 
------------------------------------------------------
------------------------------------------------------
xna40 may not install properly in Wine yet
------------------------------------------------------
Executing w_do_call dotnet40
Executing load_dotnet40 
------------------------------------------------------
This package (dotnet40) may not fully work on a 64-bit installation. 32-bit prefixes may work better.
------------------------------------------------------
------------------------------------------------------
dotnet40 does not yet fully work or install on wine.  Caveat emptor.
------------------------------------------------------
Current Wine does not have Wine bug 42701, so not applying workaround
Executing cd /root/snap/cncra2yr/common/.cache/winetricks/dotnet40
Downloading https://download.microsoft.com/download/9/5/A/95A9616B-7A37-4AF6-BC36-D6EA96C8DAAE/dotNetFx40_Full_x86_x64.exe to /root/snap/cncra2yr/common/.cache/winetricks/dotnet40
Failed to Fopen file /etc/wgetrc
Failed to Fopen file /etc/wgetrc
wget: Cannot read /etc/wgetrc (Permission denied).
--2019-07-18 01:02:54--  https://download.microsoft.com/download/9/5/A/95A9616B-7A37-4AF6-BC36-D6EA96C8DAAE/dotNetFx40_Full_x86_x64.exe
Resolving download.microsoft.com (download.microsoft.com)... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘download.microsoft.com’
Failed to Fopen file /etc/wgetrc
Failed to Fopen file /etc/wgetrc
wget: Cannot read /etc/wgetrc (Permission denied).
Failed to Fopen file /etc/wgetrc
Failed to Fopen file /etc/wgetrc
wget: Cannot read /etc/wgetrc (Permission denied).
Executing cd /root/snap/cncra2yr/common/.cache/winetricks/dotnet40
Downloading https://web.archive.org/web/2000/https://download.microsoft.com/download/9/5/A/95A9616B-7A37-4AF6-BC36-D6EA96C8DAAE/dotNetFx40_Full_x86_x64.exe to /root/snap/cncra2yr/common/.cache/winetricks/dotnet40
Failed to Fopen file /etc/wgetrc
Failed to Fopen file /etc/wgetrc
wget: Cannot read /etc/wgetrc (Permission denied).
--2019-07-18 01:02:54--  https://web.archive.org/web/2000/https://download.microsoft.com/download/9/5/A/95A9616B-7A37-4AF6-BC36-D6EA96C8DAAE/dotNetFx40_Full_x86_x64.exe
Resolving web.archive.org (web.archive.org)... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘web.archive.org’
------------------------------------------------------
Downloading https://web.archive.org/web/2000/https://download.microsoft.com/download/9/5/A/95A9616B-7A37-4AF6-BC36-D6EA96C8DAAE/dotNetFx40_Full_x86_x64.exe failed
------------------------------------------------------
user-open error: exec: "dbus-launch": executable file not found in $PATH
No protocol specified
Unable to init server: Could not connect: Connection refused

(yad:7458): Gtk-WARNING **: 01:02:54.357: cannot open display: :0
```
sorry for the troubles. i'm new to linux.

**Comment by mmtrt** [comment]
In the screenshot which is saying you to reboot your system in order to snapd function. Maybe try doing that and when you run snap don't add sudo with it.

**Comment by kiyokodyele** [comment]
![DeepinScreenshot_20190718014102](https://user-images.githubusercontent.com/45057955/61397792-3e7bbe00-a8fd-11e9-89df-0f49def3238c.png)
done copying cnc ra2/yr files
after clicking install, an error occured: `wine: Bad EXE format for Z:\tmp\CnCNet5_YR_Installer.exe.
`

**Comment by kiyokodyele** [comment]
the next time i'm running it, it's not opening anymore.

**Comment by mmtrt** [comment]
That could be due to broken download earlier or broken snap data with due to earlier path issue. You remove snap with snap remove cncra2yr and then install again

**Comment by kiyokodyele** [comment]
i tried reinstalling everything. and fixing $PATH still the same problem.

**Comment by mmtrt** [comment]
You are still getting this `wine: Bad EXE format for Z:\tmp\CnCNet5_YR_Installer.exe.`

**Comment by mmtrt** [comment]
ok now you have to manually download .net and xna copy files to cache in snap dir.
* dotnet40
[link](https://www.microsoft.com/en-pk/download/details.aspx?id=17718)
* xna40
[link](https://www.microsoft.com/en-us/download/details.aspx?id=20914)
#
remove snap data completely
* `rm -rf "$HOME/snap/cncra2yr"`
#
create winetricks cache dirs
* `mkdir -p "$HOME/snap/cncra2yr/common/.cache/winetricks/{dotnet40,xna40}"`
#
copy downloaded .net & xna40 to cache dir
* `cd Downloads`
* `cp dotNetFx40_Full_x86_x64.exe "$HOME/snap/cncra2yr/common/.cache/winetricks/dotnet40"`
* `cp xnafx40_redist.msi "$HOME/snap/cncra2yr/common/.cache/winetricks/xna40"`
#
run the snap now

**Comment by kiyokodyele** [comment]
i've tried it still doesnt fix the problem. thank you for your effort on responding. i'll close this issue now. i'll just ditch my linux. thanks again.

**Comment by mmtrt** [comment]
Thanks I've tried my best to help you solving issue, anyways good luck in your future endeavors.

**Comment by mmtrt** [comment]
Deepin os have issues with snaps getting internet connection that issue could be related to this issue and I thought inform you about this.

**Comment by kiyokodyele** [comment]
thank you for your response. i already ditched deepin os and tried linux mint. now it works properly but the only problem i encountered is that when i play the game, it is slow. graphics drivers are installed also i tried tweaking all the possible display settings but still no luck. i've noticed that one of the rendering option is not included while on windows it is exist and i think it is the 'CNCDRawCompat' if i could still remember it. I could play this game smoothly on a 1920x1080 screen resolution using windows even i am using a 2560x1080 external monitor. it is not stretched on my monitor and runs okay. but if i try the same thing on linux minit, the game display will stretch to my monitor size even if i use 1920x1080. and is also slow. maybe it is because of windows to linux  conversion process that makes it slow?
